# Generated by Django 4.2.4 on 2023-08-21 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pet',
            table='pet',
        ),
    ]
